In [28]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)

In [29]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
list(y)

[0, 1, 2, 3, 4]

In [31]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)
print("\n",X_train)
print("\n",y_train)
print("\n",X_test)
print("\n",y_test)


 [[4 5]
 [0 1]
 [6 7]]

 [2, 0, 3]

 [[2 3]
 [8 9]]

 [1, 4]
